port: 7890
socks-port: 7891
mode: rule

proxies:
  - name: "官网"
    type: http
    server: 127.0.0.1
    port: 8080

proxy-groups:
  - name: "官网"
    type: select
    proxies:
      - 官网

rules:
  - MATCH,AUTO